[pytest]
testpaths = test
python_files = test_*.py
addopts = -ra --strict-markers
filterwarnings =
    ignore::PendingDeprecationWarning
    ignore::DeprecationWarning
    ignore::RuntimeWarning
    error::DeprecationWarning:profiles(\..*)?
    error::PendingDeprecationWarning:profiles(\..*)?
    error::DeprecationWarning:test(\..*)?
